[build]
  command = "hugo -s site -c content"
  publish = "site/public"

# [context.deploy-preview]
#   command = "npm run build-preview"

# [context.deploy-preview.environment]
[context.production.environment]
  # as printed by the local command "hugo version"
  HUGO_VERSION = "0.55.6"
